<!DOCTYPE html>
<html>
  <head>
  <title>
      
          Promiseとasync/awaitをちゃんと理解する - Kazuki Koide
      
  </title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="map[]" />
  <link rel="shortcut icon" type="image/x-icon" href="https://koirand.github.io/img/favicon.ico">

  
  <link rel="stylesheet" href="https://koirand.github.io/css/style.css">
  <link rel="stylesheet" href="https://koirand.github.io/css/markdown.css">
  <link rel="stylesheet" href="https://koirand.github.io/css/syntax-highlight.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  
  

  <meta property="og:title" content="Promiseとasync/awaitをちゃんと理解する" />
<meta property="og:description" content="JavaScriptといえばコールバックだが、最近は基本的に非同期関数はPromiseで実装してasync/awaitするのがトレンドらしい" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://koirand.github.io/blog/2018/async-await/" />
<meta property="article:published_time" content="2018-10-01T00:00:00&#43;00:00"/>
<meta property="article:modified_time" content="2018-10-01T00:00:00&#43;00:00"/>

<meta itemprop="name" content="Promiseとasync/awaitをちゃんと理解する">
<meta itemprop="description" content="JavaScriptといえばコールバックだが、最近は基本的に非同期関数はPromiseで実装してasync/awaitするのがトレンドらしい">


<meta itemprop="datePublished" content="2018-10-01T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2018-10-01T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="2409">



<meta itemprop="keywords" content="" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Promiseとasync/awaitをちゃんと理解する"/>
<meta name="twitter:description" content="JavaScriptといえばコールバックだが、最近は基本的に非同期関数はPromiseで実装してasync/awaitするのがトレンドらしい"/>

  <!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
  <![endif]-->

  <!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
  <![endif]-->

  
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-126342153-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
</head>

  <body>
    
  <h1>Promiseとasync/awaitをちゃんと理解する</h1>
  <header>
  
  <div class="avatar">
    <img class="avatarMask" src="https://koirand.github.io/img/avatar.jpg">
    <a href="https://koirand.github.io/"><img src="https://koirand.github.io/img/avatar-border.svg"></a>
  </div>
  
  <h2><a class="author" href="https://koirand.github.io/">Kazuki Koide</a></h2>
</header>

  
  <p class="date">October 1, 2018</p>
  
  <div id="contentBody">
    

<p>JavaScriptといえばコールバックだが、最近は基本的に非同期関数はPromiseで実装してasync/awaitするのがトレンドらしい。もし使いたい関数がPromiseをサポートしていない場合は、自分でPromiseにラップするのが良いとのこと。この辺の知識が若干怪しかったので、実際に一からやってみた。</p>

<h2 id="コールバック方式">コールバック方式</h2>

<p>まずは、適当に従来のコールバック方式の非同期関数を書いてみる。</p>

<pre><code class="language-javascript">// コールバック方式による非同期関数
function sum (x, y, callback) {
  setTimeout(() =&gt; {
    if (typeof(x) !== 'number' || typeof(y) !== 'number') {
      callback(new Error('Invalid parameter!'), null)
      return
    }
    callback(null, x + y)
  }, 1000)
}

// 実行
sum(1, 2, (err, result) =&gt; {
  if (err) {
    console.log(err)
    return
  }
  console.log('result:', result)
})
</code></pre>

<p>sum関数は足し算をするだけの関数だが、1秒もかかってしまう。時間がかかるので非同期で動くようになっている&hellip;ということにする。これを実行すると1秒後に<code>result: 3</code>が出力される。引数に数値以外が指定された場合は以下のエラーが出力される。</p>

<pre><code>Error: Invalid parameter!
    at Timeout.setTimeout [as _onTimeout] (/xxx/sandbox/nodejs/1.callback.js:4:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
</code></pre>

<h2 id="promise方式">Promise方式</h2>

<p>次に、先ほどのsum関数をPromiseでラップする。</p>

<pre><code class="language-javascript">// コールバック方式による非同期関数(さっきと同じもの)
function sum (x, y, callback) {
  setTimeout(() =&gt; {
    if (typeof(x) !== 'number' || typeof(y) !== 'number') {
      callback(new Error('Invalid parameter!'), null)
      return
    }
    callback(null, x + y)
  }, 1000)
}

// Promiseでラップ
function promiseSum (x, y) {
  return new Promise((resolve, reject) =&gt; {
    sum(x, y, (err, result) =&gt; {
      if (err) {
        reject(err)
        return
      }
      resolve(result)
    })
  })
}

// 実行
promiseSum(1, 2).then(result =&gt; {
  console.log('result:', result)
}).catch(err =&gt; {
  console.log(err)
})
</code></pre>

<p>これがいわゆる「Promiseでラップする」ということ。これを実行しても先ほどと同様に1秒後に<code>result: 3</code>が出力される。</p>

<h2 id="コールバック方式とpromise方式の比較">コールバック方式とPromise方式の比較</h2>

<p>コールバック方式とPromise方式の実行コードを並べてみる。</p>

<pre><code class="language-javascript">// コールバック方式
sum(1, 2, (err, result) =&gt; {
  if (err) {
    console.log(err)
    return
  }
  console.log('result:', result)
})

// Promise方式
promiseSum(1, 2).then(result =&gt; {
  console.log('result:', result)
}).catch(err =&gt; {
  console.log(err)
})
</code></pre>

<p>コールバック方式の場合は、関数の仕様に合わせて例外処理する必要がある。今回だと「コールバック関数の第一引数でエラーを受け取る」という仕様だ。それがPromiseでラップすることにより、どんな関数でも同じ方法(catch)で例外処理ができる。これはPromise方式のメリットだと感じた。可読性についてはどちらも変わらないと感じる。</p>

<h2 id="非同期関数を順番に実行する">非同期関数を順番に実行する</h2>

<p>次に、1から4の数字を全て足し合わせてみる。sum関数は2つの数字しか受け取れないので、1,2の足し算の結果と3を足して、その結果と4を足すという風に順次処理を行う。それぞれ以下のようなコードになる。</p>

<h4 id="コールバック方式-1">コールバック方式</h4>

<pre><code class="language-javascript">// コールバック方式による非同期関数
function sum (x, y, callback) {
  setTimeout(() =&gt; {
    if (typeof(x) !== 'number' || typeof(y) !== 'number') {
      callback(new Error('Invalid parameter!'), null)
      return
    }
    callback(null, x + y)
  }, 1000)
}

// 実行
sum(1, 2, (err, result) =&gt; {
  if (err) {
    console.log(err)
    return
  }
  sum(result, 3, (err, result) =&gt; {
    if (err) {
      console.log(err)
      return
    }
    sum(result, 4, (err, result) =&gt; {
      if (err) {
        console.log(err)
        return
      }
      console.log('result:', result)
    })
  })
})
</code></pre>

<p>これを実行すると、足し算を３回行なっているので、３秒待ったあとに<code>result: 10</code>が出力される。良くコールバック地獄やネスト地獄と言われて問題になっているが、この程度だとコールバック方式でもそこまで地獄感は感じない。地獄を味わっている人たちはどれくらい激しいネストをしているんだろうか。</p>

<h4 id="promise方式-1">Promise方式</h4>

<pre><code class="language-javascript">// コールバック方式による非同期関数
function sum (x, y, callback) {
  setTimeout(() =&gt; {
    if (typeof(x) !== 'number' || typeof(y) !== 'number') {
      callback(new Error('Invalid parameter!'), null)
      return
    }
    callback(null, x + y)
  }, 1000)
}

// Promiseでラップ
function promiseSum (x, y) {
  return new Promise((resolve, reject) =&gt; {
    sum(x, y, (err, result) =&gt; {
      if (err) {
        reject(err)
        return
      }
      resolve(result)
    })
  })
}

// 実行
promiseSum(1, 2).then(result =&gt; {
  return promiseSum(result, 3)
}).then(result =&gt; {
  return promiseSum(result, 4)
}).then(result =&gt; {
  console.log('result:', result)
}).catch(err =&gt; {
  console.log(err)
})
</code></pre>

<p>このコードを実行した場合も、３秒待ったあとに<code>result: 10</code>が出力される。Promise方式だと、メソッドチェイン的な書き方で順番に実行でき、ネストは浅くなる。またPromise方式のもうひとつのメリットとして、try catch的な例外処理ができる。個別に例外を拾いたい場合は、以下のようにthen関数の第二引数に例外処理を書くことができる。</p>

<pre><code class="language-javascript">// 数値以外を引数に指定して故意にエラーを発生させる
promiseSum('x', 2).then(result =&gt; {
  return promiseSum(result, 3)
}, () =&gt; {
  console.log('Error handling ...')
}).then(result =&gt; {
  return promiseSum(result, 4)
}).then(result =&gt; {
  console.log('result:', result)
}).catch(err =&gt; {
  console.log(err)
})
</code></pre>

<p>この実行結果は以下となる。&rsquo;Error handling&hellip;&lsquo;を出力したあとcatchに飛んでいるのがわかる。</p>

<pre><code>Error handling ...
Error: Invalid parameter!
    at Timeout.setTimeout [as _onTimeout] (/xxx/sandbox/nodejs/5.secencial-promise2.js:4:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
</code></pre>

<h2 id="async-await方式">async/await方式</h2>

<p>冒頭に書いた通り、最近はasync/awaitを使うのがトレンドだ。先ほどのPromise方式を
async/awaitで書き換えると以下のコードになる。</p>

<pre><code class="language-javascript">// コールバック方式による非同期関数
function sum (x, y, callback) {
  setTimeout(() =&gt; {
    if (typeof(x) !== 'number' || typeof(y) !== 'number') {
      callback(new Error('Invalid parameter!'), null)
      return
    }
    callback(null, x + y)
  }, 1000)
}

// Promiseでラップ
function promiseSum (x, y) {
  return new Promise((resolve, reject) =&gt; {
    sum(x, y, (err, result) =&gt; {
      if (err) {
        reject(err)
        return
      }
      resolve(result)
    })
  })
}

// 実行
(async () =&gt; {
  try {
    let result;
    result = await promiseSum(1, 2)
    result = await promiseSum(result, 3)
    result = await promiseSum(result, 4)
    console.log('result:', result)
  } catch (err) {
    console.log(err)
  }
})()
</code></pre>

<p>このコードを実行した場合も3秒待ったあとに<code>result: 10</code>が出力される。Promise関数に<code>await</code>を付けることで処理の完了を待ってくれる。<code>await</code>は<code>async</code>を付けたfunctionの中だけで使えるというルールがあるので即時関数を使わないといけない点はイマイチだが、コールバックを使わずに同期処理が書けるので可読性が高いと感じる。普通にtry catchで例外処理できるのもポイント高い。ちなみに先ほどのように個別で例外を拾う場合は以下のようになる。</p>

<pre><code class="language-javascript">(async () =&gt; {
  try {
    let result;
    // 数値以外を引数に指定して故意にエラーを発生させる
    result = await promiseSum('x', 2).catch(err =&gt; {
      console.log('Error handling ...')
    })
    result = await promiseSum(result, 3)
    result = await promiseSum(result, 4)
    await console.log('result:', result)
  } catch (err) {
    console.log(err)
  }
})()
</code></pre>

<p>このように、catchで個別に例外を拾うことができる。コールバック完全駆逐&hellip;とまでは行かないようだ。</p>

<h2 id="async-await方式でのテスト">async/await方式でのテスト</h2>

<p>昔は、非同期処理をテストするにはco-mocha等を使った気がするが、最近はmochaでasync/awaitが使えるようだ。以下のようなテストコードになる。</p>

<pre><code class="language-javascript">describe('asunc/await test', () =&gt; {
  it('1 + 2 = 3 ', async () =&gt; {
    const result = await promiseSum(1, 2)
    assert.strictEqual(result, 3)
  })

  it('数字以外が入力されるとエラー', async () =&gt; {
    let f = () =&gt; {}
    try {
      const result = await promiseSum('x', 2)
    } catch (err) {
      f = () =&gt; {throw err}
    } finally {
      assert.throws(f, 'Invalid parameter!')
    }
  })
})
</code></pre>

  </div>
  <footer>
  <p>
  &copy; 2018 Kazuki Koide.
  Powered by <a href="https://gohugo.io/">Hugo</a>
  using the <a href="https://github.com/koirand/pulp/">pulp</a> theme.
  </p>
</footer>


  </body>
</html>
